- .travis.yml
- Update chrome driver in `.travis.yml` (since Travis has jumped to Chrome version 76).
- Update to _Ubuntu Bionic 18.04_ (from default Travis Ubuntu Trusty 14.04) as that [is now the recommended way of using `xvfb` in Travis](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui).
- Remove `apt-get install node` on Travis as that is then [pre-installed](https://docs.travis-ci.com/user/reference/bionic/#javascript-and-nodejs-support).
> Update Chrome driver and Travis dist

- .travis.yml
- README.md
- setup.py
Currently some requirements versions are given as `~= x.y.z`. This increases likelihood of version conflicts. Assuming dependencies are well behaving with respect to semantic versioning, it is better to state `~= x.y` in order to reduce risk of verson conflict. 
See [PEP 440](https://www.python.org/dev/peps/pep-0440/#compatible-release) for more information on compatible version specifiers.
> Relax minor version in dependencies

- .travis.yml
On git code release, the tag is sent to Travis. However, since artifacts are built on Travis before release, the git tag automatically changes to a `dev` tag locally.
Therefore: After building of the artifacts, set tag back to what was sent from git initially on release, and use that when deploying to pypi.
> Travis git release tag

- .travis.yml
On git code release, the tag is sent to Travis. However, since artifacts are built on Travis before release, the git tag automatically changes to a `dev` tag locally.
Therefore: After building of the artifacts, set tag back to what was sent from git initially on release, and use that when deploying to pypi.
> Specify version on Travis deploy

- src/demo/LayeredMapDemo.js
- src/lib/components/LayeredMap.js
- src/lib/private_components/layered-map-resources/DrawControls.react.js
Closes #34 
Added 3  new bool props to LayeredMap
`draw_toolbar_marker`, `draw_toolbar_polyline`, `draw_toolbar_polygon`.
When all are `false` the Leaflet Draw toolbar is not shown.
> Make leaflet draw optional

- src/lib/components/LayeredMap.js
- src/lib/private_components/layered-map-resources/OptionalLayerControl.react.js
Resolves #57. In addition, if `(more than one layer) and (only one base layer)`, the base layer selection part of the layer control is hidden (i.e. only overlay layers can be selected/deselected).
The changes are a bit involved since the conditional elements to include or not are components with children.
> Conditional layer control

- webviz_subsurface_components/__init__.py
Development tags in SCM versions has a `+` which breaks the new fingerprint system in `dash >= 1.5` (Dash  currently replace `.` with `_`, bot not other characters like `+`, see [this line](https://github.com/plotly/dash/blob/40b5357f262ac207f94ac980e6cb928d94df65b7/dash/fingerprint.py#L12)). We can solve this downstream in `webviz` by doing the replacement ourselves.
> Remove + in scm version tag as it breaks Dash's new fingerprint system

- setup.py
- webviz_subsurface_components/__init__.py
...now that the relevant `dash` issue is closed (for `dash >= 1.6`).
> Simplify versioning

- .travis.yml
- package-lock.json
- package.json
- src/lib/components/HistoryMatch.js
- src/lib/private_components/layered-map-resources/CanvasOverlay.react.js
Solves a building error with `dash==1.8` (missing proptype). Also solves a console error, apparently arising from some strange combination of importing newest `dash_core_components`, as well as indirectly importing some leaflet source files twice.
In addition, building R components now requires author email being defined in `package.json`.
> Support dash==1.8

- src/lib/components/LayeredMap.js
Default zIndex must be high as other components such as dropdowns are always rendered below the map. Setting Map zindex to 0 should solve it.
> Set LayeredMap zIndex to 0

- src/lib/components/LayeredMap.js
- Closes #101.
- Removes extra unmatched `}` which was rendered in the top left corner of the map.
> Prevent view reset onClick

- .eslintrc
- package.json
- src/lib/components/HistoryMatch.js
- src/lib/components/Map.js
- src/lib/private_components/hm-resources/history_matching.js
- src/lib/private_components/hm-resources/history_matching_plot.js
- src/lib/private_components/hm-resources/legend.js
- src/lib/private_components/layered-map-resources/CompositeMapLayer.react.js
- src/lib/private_components/layered-map-resources/DrawControls.react.js
- src/lib/private_components/map/cell.js
- src/lib/private_components/map/color-scale.js
- src/lib/private_components/map/compass.js
- src/lib/private_components/map/distance-scale.js
- src/lib/private_components/map/field.js
- src/lib/private_components/map/flow_animation.js
- src/lib/private_components/map/flow_map.js
- src/lib/private_components/map/grid.js
- src/lib/private_components/map/infobox.js
- src/lib/private_components/map/linear_algebra.js
- src/lib/private_components/map/map.js
- src/lib/private_components/map/map2d.js
- src/lib/private_components/map/particle.js
- src/lib/private_components/map/tests/arbitraries.js
- src/lib/private_components/map/tests/grid.spec.js
- src/lib/private_components/map/vertical-slider.js
- src/lib/private_components/morris-resources/morris.js
- src/lib/private_components/shared/slider.js
Closes #106. `eslint` is now turned on for all new JavaScript code.
Some of the old code ported from  https://github.com/equinor/webviz has certain `eslint` flags turned off, and should be fixed when rewriting them (if we are to keep them going forward at all).
> Run eslint during CI

- .eslintignore
- .github/workflows/webviz-subsurface-components.yml
- .gitignore
- README.md
- index.html
- package-lock.json
- package.json
- webpack.config.js
- webpack.serve.config.js
> Deploy demo app to GitHub pages automatically

- src/demo/NewLayeredMapDemo.js
- src/lib/components/NewLayeredMap/layers/L.imageWebGLOverlay.js
- src/lib/components/NewLayeredMap/layers/L.tileWebGLLayer.js
- src/lib/components/NewLayeredMap/shaders/baseFragmentShader.fs.glsl
- src/lib/components/NewLayeredMap/webgl/commands/drawWithColormap.js
Refactored the TileWebGLLayer to use canvases instead of image-tags to avoid flickering on update.
> 🚘 Refactored TileWebGLLayer to use canvases instead of images

- .github/workflows/webviz-subsurface-components.yml
...and also pin to Python version 3.7.7 while waiting for https://github.com/actions/virtual-environments/issues/1202 to be deployed.
> Update Python GitHub action version

- .babelrc.json
- package-lock.json
- package.json
- src/lib/components/Map/utils/map.js
- webpack.config.js
Closes #235.
For some reason, using `babel` to compile `javascript` + `typescript` instead of `ts-loader` (which [sometimes is recommended](https://iamturns.com/typescript-babel/) anyway due to e.g. faster compiling speed during development), the streamline animation works again.
> Fix streamline animation regression

- src/lib/components/LeafletMap/LeafletMap.jsx
- Added defaultProp for `layers` to allow initialization of the component without layer data
- Added defaultProp for `syncedMaps` to simplify the code
> Set default props in LeafletMap

- package.json
Place the javascript output files from the typescript linter in a `js_output` folder instead of `dist` as this causes problems when creating the python distribution.
> Make typescript linter use a temporary folder for js output files

- package-lock.json
- package.json
- src/lib/components/DeckGLMap/Map.tsx
- src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
- src/lib/components/WellCompletions/components/Settings/__snapshots__/HideZeroCompletionsSwitch.test.tsx.snap
- src/lib/components/WellCompletions/components/Settings/__snapshots__/RangeDisplayModeSelector.test.tsx.snap
- src/lib/components/WellCompletions/utils/dataUtil.ts
* Cleanup last few eslint warnings
* Rename `linting` to `lint`, for consistency with the other commands
* Run `npm update` to update `y18n` and get rid of the security vulnerability
> Cleanup warnings

- examples/example_well_completions.py
- package.json
> Minor fix Dash WellCompletion build and example

- examples/example_deckgl_map.py
- src/demo/example-data/deckgl-map.json
- src/lib/components/DeckGLMap/DeckGLMap.jsx
- src/lib/components/DeckGLMap/Map.tsx
Data can be specified in the `resources` dict and referenced from the DeckGL spec with the following syntax: `"@@#resources.resourceId"`.
> Add `resources` prop to the map component

- package-lock.json
- package.json
- src/lib/components/VectorSelector/components/VectorSelectorComponent.tsx
- src/lib/components/VectorSelector/utils/VectorSelection.ts
Adjusted `VectorSelection` according to changes in `SmartNodeSelector`'s `TreeData`. 
This fixes the issue where several nodes got selected when selecting a node whose name is partly contained in other names. E.g.:
Selected: `NodeName1`
Returns: `NodeName1` `NodeName12` `NodeName123` ...
This depends on newest version of `webviz-core-components` and the dependency must be adjusted.
> Adjusted to new `SmartNodeSelector`

- src/lib/components/PriorPosteriorDistribution/utils/prior_posterior_distribution.js
Bug fix to avoid that histogram bins are cut off in the PriorPosteriorDistribution component.  This is easiest accomplished by increasing the plots x range compared to the data range. 
Closes #274
> Better align bin `x` positions with input data in `PriorPosteriorDistribution`

- src/lib/components/VectorSelector/VectorSelector.jsx
- src/lib/components/VectorSelector/components/VectorSelectorComponent.tsx
This PR makes the new `lineBreakAfterTag` property from `SmartNodeSelector` available in `VectorSelector`.
Also changed default `numSecondsUntilSuggestionsAreShown` to 0.5s.
> Added `lineBreakAfterTag` property to `VectorSelector` component

- .github/workflows/webviz-subsurface-components.yml
In order to simplify the release procedure each month, we bundle the latest prerelease of `webviz-core-components` when doing prerelease of `webviz-subsurface-components` (in order to not have to manually create PR's updating `package/package-lock.json` for every prerelease of `webviz-core-components` during the release process).
When doing the final release, the `package-lock.json` is again used also for `webviz-core-components` (i.e. `package.json` and `packge-lock.json` should as normally be updated prior to final tag/release).
> Use prerelease of `webviz-core-components` on prerelease of this package

- .github/workflows/webviz-subsurface-components.yml
- react/package.json
Closes #425.
Looks like Dash wants its components to be built
1) in the same folder as `node_modules` (it needs to find `react-docgen`).
2) uses the second argument to `dash-generate-components` as both a folder and as namespace in its JavaScript-Python integration (the latter not playing nicely with `./`, `../` etc.)
> Re-enable Python tests

- react/.eslintignore
The example input files (jsons) can be very large, so they can slow down lining quite a bit.
Not linting those is a 2x faster on my computer.
> Add demo examples to eslint ignore

- react/src/lib/components/DeckGLMap/components/InfoCard.tsx
On the edges of the map component, I was getting errors for the infocard table "multiple keys with the same name exists".
It should update the value if the key exists instead of adding a new entry for the table.
> Fixed infocard issue for multiple key in table

- react/package.json
Followup after #498 (apparently input paths needs to be within quotes on Linux/Mac see [`copyfiles` documentation](https://www.npmjs.com/package/copyfiles)).
Closes #522.
> Escape `copyfiles` argument in order to work on Linux/Mac

- react/package.json
Fixes #522.
Prevented *.glsl and *.svg files from being included in npm package.
> Removed whitespace between filename suffixes.

- react/src/lib/components/DeckGLMap/components/InfoCard.tsx
Currently values in `InfoCard` are displayed with two decimals.
For absolute values < 1 this can often give a 0.00 readout.
This PR will round to two significant (non-zero) figures for those values.
.
> Round to significant value in `InfoCard`

- react/src/lib/components/DeckGLMap/storybook/DeckGLMap.stories.jsx
This will correct the order of storybook examples for DeckGLMap componet
> Renamed deckglmap storybook example

- react/src/lib/components/DeckGLMap/DeckGLMap.jsx
Docstring was not showing for the "layers" prop.
Also added reference to deck.gl documentation.
Partial fix for #292.
> Fixed docstring for "layers".

- react/src/lib/components/GroupTree/components/GroupTreeViewer.tsx
- react/src/lib/components/LayeredMap/LayeredMap.jsx
- react/src/lib/components/LayeredMap/components/DrawControls.react.js
- react/src/lib/components/LayeredMap/webgl/alter_image.js
- react/src/lib/components/LeafletMap/components/Controls/components/DrawControls.js
- react/src/lib/components/LeafletMap/components/Controls/components/MousePosition.js
- react/src/lib/components/LeafletMap/webgl/commands/drawWithTerrainRGB.js
- react/src/lib/components/Morris/Morris.jsx
- react/src/lib/components/PriorPosteriorDistribution/PriorPosteriorDistribution.jsx
- react/src/lib/components/VectorCalculator/VectorCalculator.jsx
- react/src/lib/components/VectorCalculator/components/ExpressionDescriptionTextField.tsx
- react/src/lib/components/VectorCalculator/components/ExpressionInputComponent.tsx
- react/src/lib/components/VectorCalculator/components/ExpressionInputTextField.tsx
- react/src/lib/components/VectorCalculator/components/ExpressionNameTextField.tsx
- react/src/lib/components/VectorCalculator/components/ExpressionsTable.tsx
- react/src/lib/components/VectorCalculator/components/ExpressionsTableComponent.tsx
- react/src/lib/components/VectorCalculator/components/VariablesTable.tsx
- react/src/lib/components/VectorCalculator/utils/BlinkingTableRow.tsx
- react/src/lib/components/WellCompletions/components/Settings/ZoneSelector.tsx
- react/src/lib/components/WellLogViewer/components/WellLogView.tsx
- react/webpack.config.js
Allows using react components as 3rd party libraries where consumers have not configured loaders for said files.
Fixes #717, #718
> Use inline loaders for .scss, .glsl and .css files.

- react/src/lib/components/DeckGLMap/components/InfoCard.tsx
- react/src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
Fixed crash when trajectory contains only one point Closes #771 
It will allow loading of wells if trajectory data is not available (LineString geometry)
> Fixed crash when trajectory contains only one point

- react/src/demo/VectorSelectorDemo.js
- react/src/lib/components/VectorSelector/VectorSelector.jsx
Add missing forward declared props for `SmartNodeSelector`
- Add missing props to .jsx file
- Add usage of props in demo for testing purpose
---
Closing:
* https://github.com/equinor/webviz-subsurface-components/issues/820
> Add missing props to `VectorSelector`

- react/package-lock.json
- react/src/lib/components/VectorCalculator/components/ExpressionsTable.tsx
Replaced Tooltip component from `eds` in ExpressionsTable with Tooltip component from `material-ui`
Fixed issue with tooltip not showing when utilizing the `VectorCalculator` in a modal in Dash-plugin.
---
####Resolves:
* https://github.com/equinor/webviz-subsurface-components/issues/607
> Replace `eds` Tooltip with `Material-ui` Tooltip

- react/package-lock.json
- react/package.json
- react/src/lib/components/DeckGLMap/redux/store.ts
- react/src/lib/components/GroupTree/redux/store.ts
- react/src/lib/components/WellCompletions/redux/store.ts
- react/webpack.config.js
Current changes is failing published storybook as static sb is built using production flag.
Hence using webpack-conditional-loader
> Use webpack conditional loader for resolving addon-redux dependency

- react/src/demo/example-data/deckgl-map.json
- react/src/lib/components/DeckGLMap/DeckGLMap.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
- react/src/lib/components/DeckGLMap/storybook/DeckGLMap.stories.jsx
> feat: Added prop to hide toolbar

- .github/workflows/webviz-subsurface-components.yml
CI workaround for https://github.com/plotly/dash/issues/1992.
> Pin `werkzeug` while waiting for upstream fix

- react/src/lib/components/DeckGLMap/layers/terrain/map3DLayer.ts
- react/src/lib/components/DeckGLMap/layers/terrain/terrainMapLayer.ts
- react/src/lib/components/DeckGLMap/layers/terrain/terrainmap.fs.glsl.ts
- react/src/lib/components/DeckGLMap/storybook/DeckGLMap.stories.jsx
setting colorMapClampColor to false will now make this color completely transparent.
> Fixed issue: Unexpected cutoff opacity behavior

- react/src/lib/components/DeckGLMap/components/Map.tsx
- react/src/lib/components/DeckGLMap/layers/drawing/drawingLayer.tsx
- react/src/lib/components/DeckGLMap/utils/measurement.ts
Fixes #882
Measurement tool for map
Provided Escape and Delete key functionality to remove data points while drawing polyline and polygon
> Measurement tool for map

- react/src/lib/components/DeckGLMap/components/InfoCard.tsx
- react/src/lib/components/DeckGLMap/components/__snapshots__/InfoCard.test.tsx.snap
Removing use of MuiPaper component as it affects global style (https://mui.com/material-ui/api/paper/).
Fix #763
> Map component affects global style 

- react/src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
Fix a bug described in https://github.com/equinor/webviz-subsurface-components/issues/1163
> fix WellsLayer.onClick to allow generating of onMouseEvent

- react/src/lib/components/DeckGLMap/DeckGLMap.stories.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
- react/src/lib/components/DeckGLMap/storybook/DeckGLMap.stories.jsx
fixes #1191 
Origin with CustomCameraPosition:
After set CustomCamraPosition as null:
Improvement:
> reset cameraPosition if cameraPosition is null

- react/src/lib/components/DeckGLMap/layers/piechart/pieChartLayer.ts
- tests/test_deckgl_map.py
Related to https://github.com/equinor/webviz-subsurface-components/issues/1295.
> Make pie chart work both on minified and non-minified code

- react/src/lib/components/DeckGLMap/layers/layersDefaultProps.ts
- react/src/lib/components/DeckGLMap/layers/map/fragment.fs.glsl.ts
- react/src/lib/components/DeckGLMap/layers/map/mapLayer.stories.tsx
- react/src/lib/components/DeckGLMap/layers/map/mapLayer.ts
- react/src/lib/components/DeckGLMap/layers/map/privateMapLayer.ts
- react/src/lib/components/DeckGLMap/layers/map/vertex.glsl.ts
- react/src/lib/components/DeckGLMap/layers/map/webworker.ts
- react/src/lib/components/DeckGLMap/layers/terrain/map3DLayer.ts
MapLayer now has a property "enableSmoothShading" which enabled will estimate normals for each vertex and henceenable phong (smooth) shading. Default true.
> Fixes: Phong shading for map layer #1290

- .github/workflows/webviz-subsurface-components.yml
> Update workflow to remove `node 12` deprecation warnings in CI

- react/src/lib/components/DeckGLMap/SubsurfaceViewerDashWrapper.stories.tsx
- react/src/lib/components/DeckGLMap/SubsurfaceViewerDashWrapper.tsx
- react/src/lib/components/DeckGLMap/index.js
- react/src/lib/index.js
Allows mapping annotations to views in Dash.
Example:
```
annotation: {
view_1: <ViewFooter>Hugin</ViewFooter>,
view_2: <ViewFooter>kH Netmap</ViewFooter>,
}
```
> Dash wrapper for SubsurfaceViewer

- react/src/lib/components/DeckGLMap/components/Map.tsx
The reason for this bug issue has following two probleams:
1) the bounds is not provided and once the user update the views, the bounds will not be updated and still remained as undefined, In the initiali stage, the default cal function can be called and provide a bound for it but in this case the func will not be called and thus cause the error.
2) we need to update the viewProps immediately rather than wait till the setviewProps  get the viewProps prop updated. I have put a fix for this in this PR and hopefully it address all the issues
> Bug fix for bounding undefined

- examples/example_webviz_colorlegend.py
- examples/example_webviz_continuouslegend.py
- examples/example_webviz_discretelegend.py
Issue with python examples for deckgl color legends.
Parsing the color legend from an url does not work. Changed the code to use json instead.
> Fix python color legend examples

- react/package.json
- react/src/lib/components/HistoryMatch/components/history_matching_plot.js
- react/src/lib/components/Map/utils/compass.js
- react/src/lib/components/Map/utils/map.js
- react/src/lib/components/Map/utils/map2d.js
- react/src/lib/components/Map/utils/vertical-slider.js
- react/src/lib/components/Morris/utils/morris.js
- react/src/lib/components/PriorPosteriorDistribution/utils/prior_posterior_distribution.js
- react/src/lib/shared/slider.js
We have updated `d3` version in this repository without moving some of the older components to the new syntax. This fixes that.
Closes https://github.com/equinor/webviz-subsurface/issues/1219.
> Update older components to use `d3` version 7

- setup.py
Fixes  #1545 
`ERROR tests/test_example_deckgl_3dgrid.py::test_render_deckgl_3dgrid[False] - TypeError: __init__() got an unexpected keyword argument 'desired_capabilities'`
> Pin selenium

- typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
- if this property is present here storybook will add a default function value for it making the component slow.
> Remove "onMouseEvent" property from SubsurfaceViewer.propTypes

- typescript/packages/well-log-viewer/src/utils/tracks.ts
Allow to work without color_table if meta is given
See https://github.com/equinor/webviz-subsurface-components/issues/1613
> Allow to work without color_table if meta is given

- typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
- typescript/packages/subsurface-viewer/src/layers/grid3d/privateLayer.ts
The prop "gridLines" added to Grid3d layer.
> feat(grid3d): prop to show-hide grid lines added

- .github/workflows/conventional_commit.yml
This is needed because squash and merge is the default strategy
> build: validate PR titles instead of commit messages

- .github/workflows/semantic_release.yml
Need to bypass branch protection in order to create release tags.
> build: use personal access token for semantic release

- typescript/.nxreleaserc.json
`buildTarget` should have a package name prefix (https://github.com/TheUnderScorer/nx-semantic-release/issues/65#issuecomment-1701205625)
> build: fix build target option in semantic release config

- .github/workflows/webviz-subsurface-components.yml
Needed because semantic-release updates the version in package.json.
> build: use --allow-same-version for "npm version"

- typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
- typescript/packages/subsurface-viewer/src/layers/grid3d/privateLayer.ts
- typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
- typescript/packages/subsurface-viewer/src/layers/utils/layerTools.ts
Grid3dLayer colorMapFunction accepts a constant color value to be used for coloring the layer. 
Implemented in the same manner as it was done for MapLayer
> feat(grid3d): constant color for coloring Grid3dLayer

- .github/workflows/typescript.yml
The Update Storybook starts with:
`cp -r ./storybook-static ..` which fails if this directory already exists.
The fix is to clean this directory before.
> ci: fix Update Storybook script

- typescript/packages/subsurface-viewer/src/layers/triangle/fragment.fs.glsl.ts
- typescript/packages/subsurface-viewer/src/layers/triangle/privateTriangleLayer.ts
- typescript/packages/subsurface-viewer/src/layers/triangle/triangleLayer.ts
- typescript/packages/subsurface-viewer/src/layers/triangle/vertex.glsl.ts
- typescript/packages/subsurface-viewer/src/layers/triangle/vertex_lines.glsl.ts
Will complete the fix for this issue: https://github.com/equinor/webviz-subsurface-components/issues/1724
"Performance: Apply flag "ZIncreasingDownwards" in vertex shaders for relevant layers. #1724"
This PR contains fix for the last layer in this issue: TriangleLayer.
It will also fix the readout for this layer.
> perf:  Apply flag "ZIncreasingDownwards" in vertex shaders for relevant layers. #1724

- typescript/packages/subsurface-viewer/src/layers/map/mapLayer.ts
- typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
- typescript/packages/subsurface-viewer/src/layers/map/utils.ts
- typescript/packages/subsurface-viewer/src/layers/map/vertex.glsl.ts
- typescript/packages/subsurface-viewer/src/layers/map/vertex_lines.glsl.ts
- This is related to earlier commit. MapLayer was missing.
-  Earlier commit: "performance:  Apply flag "ZIncreasingDownwards" in vertex shaders for relevant layers. 
#1724 (#1737)"
> perf:  Apply flag "ZIncreasingDownwards" in vertex shaders MapLayer.

- .github/workflows/typescript.yml
The tests were not run due to misuse of `concurrently`
> test: fix storybook test runner

- typescript/packages/subsurface-viewer/src/components/Map.tsx
- typescript/packages/subsurface-viewer/src/layers/map/mapLayer.stories.tsx
I had to split an effect to accomplish this.
> fix: If camera or bounds property is set, the view should not change when adding a layer.

- typescript/packages/subsurface-viewer/src/layers/grid3d/webworker.ts
This will fix the following webviz  issue: "Grid3DLayer: surfaces are not displayed on firefox #1765"
- To many vertices was reported to webgl.
> fix: "Grid3DLayer: surfaces are not displayed on firefox"

- typescript/packages/subsurface-viewer/src/layers/points/pointsLayer.ts
- typescript/packages/subsurface-viewer/src/layers/polylines/polylinesLayer.ts
- This is a fix of webviz issue: "Point layer and line layer cursor readout not working #1655"
- https://github.com/equinor/webviz-subsurface-components/issues/1655
> fix: Point layer and line layer cursor readout not working

- typescript/package-lock.json
- typescript/packages/subsurface-viewer/package.json
- typescript/packages/well-log-viewer/package.json
Prevents overriding background color css.
Fixes #1752
> fix: bump to latest @emerson-eps/color-tables

- typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
BREAKING CHANGE: Remove obsolete "toolbar" and "colorLegend" props
> refactor(subsurface-viewer)!: remove obsolete props

- typescript/packages/subsurface-viewer/src/components/Map.tsx
- used to be single click
- May be possible to remove the typecheck complaint if anybody has a suggestion.
> fix: Use double click to center component on mouse position.

- typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
- typescript/packages/subsurface-viewer/src/components/Map.tsx
- typescript/packages/subsurface-viewer/src/components/__snapshots__/Map.test.tsx.snap
- typescript/packages/subsurface-viewer/src/components/settings/LayersButton.test.tsx
- typescript/packages/subsurface-viewer/src/layers/axes/axesLayer.ts
- typescript/packages/subsurface-viewer/src/layers/colormap/colormapLayer.ts
- typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
- typescript/packages/subsurface-viewer/src/layers/hillshading2d/hillshading2dLayer.ts
- typescript/packages/subsurface-viewer/src/layers/map/mapLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/layers/map/mapLayer.ts
- typescript/packages/subsurface-viewer/src/layers/points/pointsLayer.ts
- typescript/packages/subsurface-viewer/src/layers/polylines/polylinesLayer.ts
- typescript/packages/subsurface-viewer/src/layers/terrain/map3DLayer.ts
- typescript/packages/subsurface-viewer/src/layers/triangle/triangleLayer.ts
- typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
- typescript/packages/subsurface-viewer/src/storybook/SubsurfaceViewer.stories.tsx
Fix for #1820 
Add formal size state and effect to retrieve size from deck ref for code clarity
Move global bounding box handling to React reducer instead of useEffect.
Move camera computation to useMemo instead of useEffect.
Memoize viewPortMargins and deckGLLayers
Add a new story displaying the subsurface viewer in tabs to reproduce the issue
Note that this is a first step to reduce the number of useEffect in the Map component
> fix: camera state when hidden page is rendered

- python/src/components/WellLogViewer/WellLogViewer.tsx
- typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
- typescript/packages/well-log-viewer/src/WellLogViewer.tsx
1. Remove unused 'domain' prop in python\src\components\WellLogViewer\WellLogViewer.tsx
2. Fix WellLogViewer props copying to WellLogView object
3. Fix bug in 'domain' prop handling in SyncLogViewer. Close #1773
> fix: 'domain' prop handling in WellLogViewer/SyncLogViewer

- typescript/packages/well-log-viewer/src/WellLogViewer.stories.tsx
- typescript/packages/well-log-viewer/src/components/WellLogView.tsx
1) fix initial **domain** and **selection** props processing
2) add **domain** and **selection** props to WellLogViewer storybook example
> fix: Process initial domain and selection props in WelLogView

- typescript/packages/subsurface-viewer/src/components/Map.tsx
- typescript/packages/subsurface-viewer/src/layers/map/webworker.ts
Fix missing dependency to recompute camera state
Fix wrong Z range for non mesh grids
Optimize bounding box update when the bounding box is not changing
Some camera computation issues where introduced in PR #1837
> fix: camera computation in some cases

- typescript/package-lock.json
- typescript/packages/subsurface-viewer/src/components/Map.tsx
- typescript/packages/subsurface-viewer/src/storybook/examples/CameraControlExamples.stories.tsx
Fix regression introduced in #1837.
Revert to use initial precedence to compute camera in 2D:
- camera if provided,
- 2D bounds if provided,
- default computation otherwise
Add story to demonstrate how to sync 2 SubSurfaceViewer.
> fix: wrong camera computation in 2D when bounds are provided

- .gitignore
- typescript/packages/subsurface-viewer/src/components/Map.tsx
- typescript/packages/subsurface-viewer/src/storybook/examples/CameraControlExamples.stories.tsx
Now the Z scaling applies to the SubSurfaceViewer that has the focus (ie. the one selected).
Update SyncedCameraSettingsComponent to control camera sync (on/off).
> fix: zoom keys (arrow up and down) only apply to last SubSurfaceViewer

- typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
- typescript/packages/well-log-viewer/src/WellLogViewer.tsx
- typescript/packages/well-log-viewer/src/__snapshots__/SyncLogViewer.test.tsx.snap
- typescript/packages/well-log-viewer/src/__snapshots__/WellLogViewer.test.tsx.snap
- typescript/packages/well-log-viewer/src/components/InfoPanel.tsx
- typescript/packages/well-log-viewer/src/components/WellLogView.tsx
- typescript/packages/well-log-viewer/src/components/WellLogViewWithScroller.tsx
- typescript/packages/well-log-viewer/src/components/__snapshots__/InfoPanel.test.tsx.snap
- typescript/packages/well-log-viewer/src/components/__snapshots__/ZoomSlider.test.tsx.snap
1. fix drawing of InfoPanel to prevent table cells size when the its values change (Closes: #1864)
2. fix a text wrapping in the value cells (See #1874 item 2)
3. fix updateReadoutPanel when InfoPanel group is clicked (Closes: #1878)
4. fix mouse tracking for displaying info panel  (Closes: #1785)
> fix: InfoPanel drawing in WellLogViewer

- typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
- typescript/packages/subsurface-viewer/src/__snapshots__/SubsurfaceViewer.test.tsx.snap
- typescript/packages/subsurface-viewer/src/components/Map.tsx
- typescript/packages/subsurface-viewer/src/components/StatusIndicator.tsx
- typescript/packages/subsurface-viewer/src/components/__snapshots__/Map.test.tsx.snap
- typescript/packages/subsurface-viewer/src/components/__snapshots__/StatusIndicator.test.tsx.snap
- typescript/packages/subsurface-viewer/src/storybook/examples/RenderingExamples.stories.tsx
The client code can handle the assets loading feedback on its own using isRenderedCallback. This way it can control the look, feel and layout of this feedback, and will prevent possible inference with application own components.
BTW, this default feedback gets centered in the PR.
Viewers team has an example where the feedback component does move the application components...
> fix: do not display "Loading assets" feedback when isRenderedCallback exists

- typescript/packages/subsurface-viewer/src/components/Map.tsx
The camera should be updated on resize, except if the user manipulated it meanwhile.
> fix: camera update on resize

- python/webpack.config.js
- typescript/.storybook/main.js
- typescript/package-lock.json
- typescript/package.json
- typescript/packages/subsurface-viewer/package.json
- typescript/packages/subsurface-viewer/src/components/Map.tsx
- typescript/packages/subsurface-viewer/src/layers/triangle/triangleLayer.ts
- typescript/packages/subsurface-viewer/src/layers/triangle/webworker.ts
- typescript/packages/subsurface-viewer/src/storybook/layers/Axes2DLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/storybook/layers/BoxSelectionLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/storybook/layers/Grid3DLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/storybook/layers/NorthArrow3DLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/storybook/layers/PointsLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/storybook/layers/PolylinesLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/storybook/layers/TriangleLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/storybook/layers/WellMarkersLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/storybook/layers/WellsLayer.stories.tsx
Creating too many webworkers is bad and leads to out of memory (OOM) errors (more or less quickly, depending on the web bundle size).
This work is about moving to controller web worker pools, first for triangle layer.
It contains:
* reproducing the issue in storybook
- Add story generating many TriangleLayers with 1 triangle each
The goal is to force spanning may webworkers to reach an OOM issue.
I got the OOM with 1200+ layers (note that client reached it with ~200 layers, probably of bigger web bundles)
- Add story with 1 TriangleLayers displaying many triangles
The goal is to check behavior if 1 triangle layer takes a lot of time
- Add triggerHome to all the stories
* Fix endless rendering (in fact no rendering at all), thus never ending "Loading assets..."
Issue revealed by the new …
> feat: use webworker pool to control number of workers

- typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
- typescript/packages/subsurface-viewer/src/components/Map.tsx
- typescript/packages/subsurface-viewer/src/storybook/examples/CameraControlExamples.stories.tsx
- typescript/packages/subsurface-viewer/src/views/viewport.ts
Changing `verticalScale` in the `views` prop does not work, as it will reset the camera target when `view` changes.
> feat: move vertical scale to SubsurfaceViewer props

- .github/workflows/python.yml
- README.md
When moving to use Red Hat Enterprise Linux 8 we would benefit from also moving toward using python version 3.11.
We strongly encourage components part of komodo to add support and testing for this version, to allow this move/upgrade to happen in near future.
Resolves #1909
> fix: Support Python 3.11

- .github/dependabot.yml
The default behavior of dependabot is to generate one PR for each dependency that needs to be updated. This leads to multiple PRs for related dependencies, while related dependencies should be handled together. For example storybook and 7 @storybook/* packages have the same version number, and should be handled as a whole.
This PRs groups some dependencies:
- react
- deckgl
- storybook
> chore: group some dependencies for dependabot

- typescript/package-lock.json
- typescript/package.json
- typescript/packages/subsurface-viewer/package.json
- typescript/packages/well-log-viewer/package.json
@webviz/subsurface-viewer clients are now responsible to install both react-redux and @reduxjs/toolkit. Both packages are now handled as peer dependencies.
> feat: add support for react-redux v9 and @reduxjs/toolkit v2 as optional peer dependencies

- typescript/packages/well-log-viewer/src/WellLogViewer.tsx
Resolves issue #2216 
The callback manager events introduced in PR #2196 where being set up in the _constructor_ hook, not in the `componentDidMount()` hook, which is against React guidelines.
This PR fixes that
> fix: Well Log Viewer - Moved callback subscription to well-log-viewer mounted hook

- typescript/packages/well-log-viewer/src/SyncLogViewer.stories.tsx
- typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
- typescript/packages/well-log-viewer/src/components/WellLogSpacer.tsx
A fix for #2241
Spacer width was not passed down to spacer component thus its width was originally 1 upon initial mounting and then it was calculated from the combination of width of the internal elements.
After the fix, the width is passed down as initial width which (if large enough)has the potential not to be recalculated.
Story with spacers as well as default spacer size was adjusted to provide a more logical spacer size upon rendering (determined from a Full HD 1080p resolution)
> fix: pass width prop to spacer component to be used for initial layout calculation

- typescript/packages/well-completions-plot/src/components/WellsPlot.tsx
- typescript/packages/well-completions-plot/src/utility-lib/stringUtils.ts
Adjusted comments, with "feat:" prefix to trigger release of `well-completions-plot` package.
Previous commit to master with "feat!:" prefix did not trigger release of package.
> feat: Trigger release for new well-completions-plot package

- typescript/packages/well-log-viewer/src/components/WellLogView.tsx
Vertical scroll position is updated every time the component is resized, when the component is hidden its size becomes zero which triggers an update of the scroll position - however in this case the position updates to 0,0 due to all sizes equal to 0 while hidden. This causes the scroll position to be "forgotten" and reset to 0 upon show and then hide of the component. 
The problem could be clearly visible in story "welllogviewer-demo-classificationlayout--rtc-tabs-layout" where the component is positioned in a tab container. When switching to a tab2 to see the component and then to tab3 or tab1 and then back to tab2 the scroll position is reset.
> fix: prevent update of scroll position when component is hidden

- typescript/packages/well-completions-plot/src/utility-lib/wellSortUtils.test.ts
- typescript/packages/well-completions-plot/src/utility-lib/wellSortUtils.ts
Improve sorting of wells when sorting by stratigraphy depth.
- Improve sorting to look at all zones with open completions when sorting.
- Update unit tests
---
**Summary:**
The sorting now creates an array of zone indices with open completion. This array is sorted with increasing indices. Comparison function then looks on element by element and compares the zone index for each well. The array with lowest zone index (i.e. shallowest zone) will be placed first in ascending sort, or last for descending sort. Continues as long the zone index values are equal. If common part is equal and one list is longer than the other, it means it has more completions - thus placed first for ascending order, or last for descending order. Otherwise arrays are equal.
> fix: Improve sort by stratigraphy depth in utility-lib for well-completions-plot

- python/package-lock.json
- python/package.json
- typescript/package-lock.json
- typescript/packages/subsurface-viewer/package.json
- typescript/packages/well-log-viewer/package.json
Bump @emerson-eps/color-tables from 0.4.61 to 0.4.85 in python
Bump @emerson-eps/color-tables from 0.4.71 to 0.4.85 in subsurface-viewer
Bump @emerson-eps/color-tables from 0.4.71 to 0.4.85 in well-log-viewer
> fix: bump @emerson-eps/color-tables to 0.4.85 in subsurface-viewer, well-log-viewer and python

- typescript/package-lock.json
- typescript/packages/subsurface-viewer/package.json
Bumps workerpool from 9.1.3 to 9.2.0 in subsurface-viewer.
> fix: bump workerpool from 9.1.3 to 9.2.0 in subsurface-viewer

- typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
- typescript/packages/well-log-viewer/src/WellLogViewer.tsx
- typescript/packages/well-log-viewer/src/components/WellLogView.tsx
To improve interactivity, we need an indication that mouse is no longer on top of well tracks. 
In this PR a new event is added which is called when the mouse exists the overlay area of the WellLogView.
> feat: Add and event to indicate mouse has left tracks area

- typescript/packages/subsurface-viewer/src/components/Map.tsx
Consider the following webviz react property that controls the readout popup:
/**
* Parameters for the InfoCard component
*/
coords?: {
visible?: boolean | null;
multiPicking?: boolean | null; 
pickDepth?: number | null;
};
The pickDepth has a default value of 10. This slows down the readout considerably for large sets of data like for instance a big map.
When hovering over object in the view, pickDepth larger than one will cause the readout to also display values for objects hidden behind the closest.
I'm am changing the default value to 2. This will remedy the slow readout and will be enough to show readout for for instance a well and a map behind it. Or 2 wells on top of each other. If one wants more pickDepth one will explicitly have to set this property.
> feat: Fixes: [NGRM]: Slow readout caused by high pick depth when displaying readout data.

- typescript/packages/subsurface-viewer/src/layers/grid3d/cellProperty.fs.glsl.ts
Can be reproduced by using the for example following properties on Grid3DLayer:
```
.
.
undefinedPropertyValue: 4,
undefinedPropertyColor: [255, 0, 0],
.
.
```
Or any other value specifying undefined properties.
> fix: [NGRM]: Grid3DLayer reports wrong x,y,z and dept values in readout for undefined property values. #2474

- typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
The z coordinates given from the `WellsLayer` to the `WellLabelLayer` are always increasing upwards
> fix: prevent flipping well label z coordinates

- typescript/packages/well-log-viewer/src/utils/tracks.ts
This PR adds a small fix to make it so a well log viewer without any tracks still renders the full axis curves and any potential well-picks. Would be helpful for some user flows in our webviz project
Before             |  After
:-------------------------:|:-------------------------:
> fix: Made Well Log Viewer set correct bounds even if no tracks are present

- .github/workflows/semantic_release.yml
- .github/workflows/typescript.yml
- typescript/package-lock.json
- typescript/package.json
- typescript/packages/group-tree-plot/package.json
- typescript/packages/group-tree-plot/project.json
- typescript/packages/subsurface-viewer/package.json
- typescript/packages/subsurface-viewer/project.json
- typescript/packages/well-completions-plot/package.json
- typescript/packages/well-completions-plot/project.json
- typescript/packages/well-log-viewer/package.json
- typescript/packages/well-log-viewer/project.json
- typescript/packages/wsc-common/package.json
- typescript/packages/wsc-common/project.json
Removes dependency on `@theunderscorer/nx-semantic-release`
Fixes #2547
> ci: migrate to `nx release` for semantic releases

- typescript/package-lock.json
This reverts commit 8cb1b017f58c1975df9db7920a94cffb8720ed1f.
The commit was an automatic commit created by `nx release`, which for some reason corrupted the `package-lock.json` file.
Likely related to this Nx bug: https://github.com/nrwl/nx/issues/22066
> ci: revert "chore(release): publish"

- typescript/packages/subsurface-viewer/src/components/ColorLegend.test.tsx
- typescript/packages/subsurface-viewer/src/components/ColorLegend.tsx
- typescript/packages/subsurface-viewer/src/components/ColorLegends.tsx
- typescript/packages/subsurface-viewer/src/components/Map.tsx
- typescript/packages/subsurface-viewer/src/layers/axes/boxLayer.ts
- typescript/packages/subsurface-viewer/src/layers/colormap/colormapLayer.ts
- typescript/packages/subsurface-viewer/src/layers/drawing/drawingLayer.tsx
- typescript/packages/subsurface-viewer/src/layers/gpglLayers/typeDefs.ts
- typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
- typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
- typescript/packages/subsurface-viewer/src/layers/grid3d/typeDefs.ts
- typescript/packages/subsurface-viewer/src/layers/map/mapLayer.ts
- typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
- typescript/packages/subsurface-viewer/src/layers/polylines/polylinesLayer.ts
- typescript/packages/subsurface-viewer/src/layers/selectable_geojson/selectableGeoJsonLayer.ts
- typescript/packages/subsurface-viewer/src/layers/triangle/privateTriangleLayer.ts
- typescript/packages/subsurface-viewer/src/layers/triangle/triangleLayer.ts
- typescript/packages/subsurface-viewer/src/layers/utils/colormapTools.ts
- typescript/packages/subsurface-viewer/src/layers/utils/layerTools.ts
- typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
- typescript/packages/subsurface-viewer/src/storybook/layers/MapLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/utils/index.ts
- typescript/packages/subsurface-viewer/src/utils/serialize.test.ts
- typescript/packages/subsurface-viewer/src/utils/serialize.ts
- typescript/packages/subsurface-viewer/src/utils/typedArray.test.ts
- typescript/packages/subsurface-viewer/src/utils/typedArray.ts
- move Material definition to own file to share it
add compatibility test (at compilation time) with @deck.gl Material version
- move loadFloat32Data to own file to share it
Added unit tests
- move DeckGLLayerContext from Map.tsx to layerTools.ts
- rename ExtendedLayer to ExtendedLegendLayer in layerTools.ts
- reorder some imports
- add new colormapTools.ts file to centralize and share:
- getImageData function
- createColormapTexture function
- ColorMapFunctionType, IColormapHints, TColorTable and TColormapDef types
- introduce typed array helper functions in own file
> chore: [NGRM] refactoring

- typescript/packages/subsurface-viewer/src/layers/triangle/line.fs.glsl.ts
- typescript/packages/subsurface-viewer/src/layers/triangle/line.vs.glsl.ts
Add DECKGL_FILTER_GL_POSITION to triangle line vertex shader for consistency with triangle vertex shader
> fix: make triangle line shader consistent with triangle shader

- typescript/package-lock.json
- typescript/packages/subsurface-viewer/package.json
Bump @deck.gl-community/editable-layers from 9.1.0-beta.4 to 9.1.1
> fix: bump @deck.gl-community/editable-layers
