equinor/webviz-subsurface-components

- src/lib/components/LayeredMap.js
> Add height as prop

- src/lib/private_components/layered-map-resources/Colormap.react.js
> Use react portal for colorbar

- examples/example_layered_map.py
- src/demo/LayeredMapDemo.js
- src/demo/example-data/layered-map.json
- src/lib/components/LayeredMap.js
Resolves #62 and resolves #64.
> Optional reset of zoom+pan and sync between instances

- .travis.yml
- examples/example_hm.py
- setup.py
- tests/test_hm.py
> Fix history match example

- package-lock.json
- package.json
- src/lib/components/LayeredMap.js
- src/lib/private_components/map/cell.js
- src/lib/private_components/map/tests/arbitraries.js
- src/lib/private_components/morris-resources/morris.js
Update `webpack`, and lock file for other dependencies. The linter `prettier` has apparently changed preferred style slightly, which therefore required some small linting changes.
> Update npm dependencies

- src/lib/components/Map.js
> Remove unnecessary margin

- .gitignore
- examples/example_hm.py
- src/lib/private_components/hm-resources/legend.js
- src/lib/private_components/morris-resources/morris.js
Mainly code improvement suggestions from lgtm.
> Small fixes

- src/lib/private_components/layered-map-resources/Switch.react.js
> Use theme font in switch

- src/lib/private_components/prior-posterior-distribution/prior_posterior_distribution.css
- src/lib/private_components/prior-posterior-distribution/prior_posterior_distribution.js
- src/lib/private_components/shared/slider.css
- Add tooltip for histogram (showing percent)
- Fix location for tooltip on realization point cloud (currently it is rendered too far to the right in some scenarios).
> Tooltip location and content prior/posterior

- src/lib/components/PriorPosteriorDistribution.js
- src/lib/private_components/prior-posterior-distribution/prior_posterior_distribution.js
- src/lib/private_components/shared/slider.css
- src/lib/private_components/shared/slider.js
Closes https://github.com/equinor/webviz-subsurface/issues/262.
> Keep iteration and bin number on parameter change

- setup.py
> Relax dependency version specifiers

- .github/workflows/webviz-subsurface-components.yml
- README.md
Also make sure `git rm -f *` does not fail if there are no files to remove.
> Add link to doc in README

- src/demo/NewLayeredMapDemo.js
- src/lib/components/NewLayeredMap/LayeredMap.js
- src/lib/components/NewLayeredMap/components/Controls.js
- src/lib/components/NewLayeredMap/components/VerticalZoom.js
- src/lib/components/NewLayeredMap/controls/L.VerticalZoom.js
- src/lib/index.js
Added functionality for scaling in the Y axis in the new LayeredMap-component - based on prop-configuration.
> NewLayeredMap: Implemented functionality to scale in the Y-axis

- examples/example_new_layered_map.py
- src/demo/NewLayeredMapDemo.js
- src/demo/example-data/new-layered-map.json
- src/lib/components/NewLayeredMap/NewLayeredMap.js
- src/lib/components/NewLayeredMap/components/Controls.js
- src/lib/components/NewLayeredMap/components/Switch.js
- src/lib/components/NewLayeredMap/components/VerticalZoom.js
- src/lib/components/NewLayeredMap/controls/L.SwitchControl.js
Added a way to add a toggle-switch in the map with props.
> 🚀 Added a switch

- src/demo/NewLayeredMapDemo.js
- src/lib/components/NewLayeredMap/NewLayeredMap.jsx
- src/lib/components/NewLayeredMap/README.md
- src/lib/components/NewLayeredMap/components/CompositeMapLayers.js
- src/lib/components/NewLayeredMap/components/DrawControls.js
> improve syncDraw functionality

- .github/workflows/webviz-subsurface-components.yml
...since GitHub workflow has fixed it upstream.
> Remove explicit 3.7.7 version in CI

- src/lib/components/LeafletMap/components/Controls/components/MousePosition.js
Round z-value to two non-zero decimals for values < 1 and two decimals for values > 1.
https://stackoverflow.com/a/40843346
Closes #228
> Improved rounding of z-value

- src/lib/components/LeafletMap/README.md
- src/lib/components/LeafletMap/components/CompositeMapLayers.js
> Calculate bounds when first receiving layers

- src/lib/components/HistoryMatch/components/history_matching_plot.js
> Shifted legend colors for simulated values too high and too low

- .github/workflows/webviz-subsurface-components.yml
- examples/example_prior_posterior.py
- examples/well-completions-csv2json.py
Bandit wasn't running on the `examples` folder because of a leading `/`.
> Fix the bandit command in the CI script

- .github/workflows/webviz-subsurface-components.yml
- .gitignore
- package-lock.json
- package.json
* Setup deckgl types as part of the postscript
* Add .vscode to gitignore
> Minor maintenance

- src/demo/example-data/deckgl-map.json
- src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
As there can be multiple log runs, added support to select a log run
> Added support to select logrun for log data

- src/lib/components/VectorSelector/components/VectorSelectorComponent.tsx
See https://github.com/equinor/webviz-core-components/pull/151.
> `VectorSelector` : Adjusted according to changes in `SmartNodeSelector`

- .github/workflows/webviz-subsurface-components.yml
- react/src/demo/example-data/deckgl-map.json
Changes:
* Fix data paths
* Fix gh-pages deployement
> Refactor codebase

- .github/workflows/webviz-subsurface-components.yml
Setup copied from `webviz-core-components`. A bit difficult to test before doing a tag in GitHub, so there might be a follow up PR if it doesn't work on first try. :laughing:
> Add `npm` deploy to CI/CD workflow

- react/package.json
> Fix postinstall on windows command prompt

- react/src/demo/example-data/deckgl-map.json
- react/src/lib/components/DeckGLMap/layers/wells/utils/spline.ts
- react/src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
> Refactoring.

- react/package-lock.json
Update `tar` to a newer version to fix security issue.
> Fix dependabot warning

- examples/example_well_logs.py
- react/src/lib/components/WellLogViewer/WellLogViewer.tsx
- react/src/lib/components/WellLogViewer/components/WellLogView.tsx
- react/src/lib/components/WellLogViewer/components/styles.scss
The well log view didn't vertically scale to fill the parent. Also, horizontal scrolling was broken on chrome.
> Fix Well Log size issues

- react/src/lib/components/GroupTree/components/GroupTreeComponent.tsx
- react/src/lib/components/GroupTree/components/GroupTreeViewer.tsx
- react/src/lib/components/GroupTree/components/Plot/group_tree.js
- element that will contain the plot
> Removed hardcoding of element id.

- react/src/lib/components/DeckGLMap/components/InfoCard.tsx
- react/src/lib/components/DeckGLMap/layers/utils/layerTools.ts
- react/src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
Add color tag on wells properties in info card for readability.
> add color tag to wells properties in info card

- examples/example_deckgl_map.py
- react/src/lib/components/DeckGLMap/DeckGLMap.jsx
- react/src/lib/components/DeckGLMap/components/DistanceScale.tsx
> Sensible default values for distance scale.

- react/src/demo/example-data/deckgl-map.json
- react/src/lib/components/DeckGLMap/layers/drawing/drawingLayer.tsx
Now from dash selected drawing feature can be selected by indexing the data using following attributes:
1. selectedFeatureIndexes: contains indexes of currently drawn/selected feature
2. data: contains list of all the drawn features.
*it also avoids duplication of data
> Fixed editing of features in drawing layer

- react/package-lock.json
- react/src/lib/components/DeckGLMap/DeckGLMap.jsx
- react/src/lib/components/DeckGLMap/components/DeckGLWrapper.tsx
- react/src/lib/components/DeckGLMap/storybook/DeckGLMap.stories.jsx
- react/src/lib/components/DeckGLMap/storybook/components/colorLegends/ContinuousLegend.stories.jsx
- react/src/lib/components/DeckGLMap/storybook/components/colorLegends/DiscreteLegend.stories.jsx
Any standard deckgl layer can be added as a layer to map component.
> Storybook example to additional deckgl layer 

- react/src/demo/example-data/deckgl-map.json
- react/src/demo/example-data/welllayer_template.json
- react/src/lib/components/DeckGLMap/DeckGLMap.jsx
- react/src/lib/components/DeckGLMap/components/DeckGLView.tsx
- react/src/lib/components/DeckGLMap/components/DeckGLWrapper.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
- react/src/lib/components/DeckGLMap/components/settings/DrawModeSelector.test.tsx
- react/src/lib/components/DeckGLMap/components/settings/LayerProperty.test.tsx
- react/src/lib/components/DeckGLMap/components/settings/LayerProperty.tsx
- react/src/lib/components/DeckGLMap/components/settings/LayerProperty_performance.test.tsx
- react/src/lib/components/DeckGLMap/components/settings/LayerSettingsButton.test.tsx
- react/src/lib/components/DeckGLMap/components/settings/LayerSettingsButton.tsx
- react/src/lib/components/DeckGLMap/components/settings/LayersButton.test.tsx
- react/src/lib/components/DeckGLMap/components/settings/LayersButton.tsx
- react/src/lib/components/DeckGLMap/components/settings/Settings.tsx
- react/src/lib/components/DeckGLMap/components/settings/__snapshots__/LayersButton.test.tsx.snap
- react/src/lib/components/DeckGLMap/components/settings/__snapshots__/Settings.test.tsx.snap
- react/src/lib/components/DeckGLMap/layers/layersDefaultProps.ts
- react/src/lib/components/DeckGLMap/layers/utils/layerTools.ts
- react/src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
- react/src/lib/components/DeckGLMap/redux/actions.ts
- react/src/lib/components/DeckGLMap/redux/reducer.ts
- react/src/lib/components/DeckGLMap/redux/store.ts
- react/src/lib/components/DeckGLMap/test/TestWrapper.tsx
- react/src/lib/components/DeckGLMap/test/testReduxState.ts
- react/src/lib/components/DeckGLMap/utils/specExtractor.ts
Improvised prop for multiple view.
views: {
layout: [number, number],
viewports: [
{
id: string,
show3D: boolean,
layerIds: string[]
}
]
}
> Multi view

- react/src/demo/example-data/deckgl-map.json
- react/src/lib/components/DeckGLMap/components/DeckGLWrapper.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
- react/src/lib/components/DeckGLMap/components/settings/LayersButton.tsx
- react/src/lib/components/DeckGLMap/components/settings/Settings.tsx
- react/src/lib/components/DeckGLMap/layers/layersDefaultProps.ts
- react/src/lib/components/DeckGLMap/layers/utils/layerTools.ts
> Fixed deckgl map to add and remove layers

- react/src/lib/components/DeckGLMap/components/settings/LayerSettingsButton.test.tsx
- react/src/lib/components/DeckGLMap/components/settings/LayerSettingsButton.tsx
- react/src/lib/components/DeckGLMap/components/settings/LayersButton.test.tsx
- react/src/lib/components/DeckGLMap/components/settings/LayersButton.tsx
- react/src/lib/components/DeckGLMap/redux/reducer.ts
> Fixed click propagation on drawing layer

- react/src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
> Fixed wells read out issue in 3d view

- react/src/lib/components/WellLogViewer/SyncLogViewer.stories.jsx
- react/src/lib/components/WellLogViewer/SyncLogViewer.tsx
- react/src/lib/components/WellLogViewer/WellLogViewer.stories.jsx
- react/src/lib/components/WellLogViewer/WellLogViewer.tsx
- react/src/lib/components/WellLogViewer/components/WellLogView.stories.jsx
- react/src/lib/components/WellLogViewer/components/WellLogView.tsx
- react/src/lib/components/WellLogViewer/components/WellLogViewWithScroller.tsx
Props to Hide/Show title and legend of the tracks in WellLogView 
#801 #803
> Props for well log track title and legend visibility

- react/src/demo/example-data/deckgl-map.json
- react/src/lib/components/DeckGLMap/DeckGLMap.tsx
- react/src/lib/components/DeckGLMap/components/InfoCard.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
- react/src/lib/components/DeckGLMap/components/ViewFooter.tsx
- react/src/lib/components/DeckGLMap/components/settings/Settings.tsx
- react/src/lib/components/DeckGLMap/components/settings/__snapshots__/Settings.test.tsx.snap
- react/src/lib/components/DeckGLMap/layers/utils/layerTools.ts
- react/src/lib/components/DeckGLMap/storybook/DeckGLMap.stories.jsx
"views": {
"showLabel": false,
"viewports": [
{
"id": "view_1",
"name"?: "Main view",
"show3D"?: false,
"layerIds":? []
}
]
}
Default label is generated if not supplied. Label visibility is controlled by a global flag "showLabel".
Closes #773
> Labels for views

- react/src/demo/example-data/welllog_template_1.json
- react/src/lib/components/WellLogViewer/components/WellLogTemplateTypes.ts
- react/src/lib/components/WellLogViewer/components/WellLogView.tsx
- react/src/lib/components/WellLogViewer/components/styles.scss
- react/src/lib/inputSchema/WellLogTemplate.json
- Define schema for well log template format
- Validate template against the schema in WellLogView component
https://github.com/equinor/webviz-subsurface-components/issues/508
> WellLog Template JSON Schema Validation

- react/src/lib/components/WellLogViewer/SyncLogViewer.stories.jsx
- react/src/lib/components/WellLogViewer/SyncLogViewer.tsx
- react/src/lib/components/WellLogViewer/WellLogViewer.stories.jsx
- react/src/lib/components/WellLogViewer/WellLogViewer.tsx
- react/src/lib/components/WellLogViewer/components/LocalMenus.tsx
- react/src/lib/components/WellLogViewer/components/PlotDialog.tsx
- react/src/lib/components/WellLogViewer/components/WellLogTemplateTypes.ts
- react/src/lib/components/WellLogViewer/components/WellLogTypes.ts
- react/src/lib/components/WellLogViewer/components/WellLogView.stories.jsx
- react/src/lib/components/WellLogViewer/components/WellLogView.tsx
- react/src/lib/components/WellLogViewer/components/WellLogViewWithScroller.stories.jsx
- react/src/lib/components/WellLogViewer/components/WellLogViewWithScroller.tsx
- react/src/lib/components/WellLogViewer/utils/tracks.ts
- react/src/lib/inputSchema/WellLog.json
- Create Well Log file JSON schema (See #487)
- Add schema validation to WellLogViewer component
- Fix template schema validation in WellLogViewer component
> Well log data file JSON schema

- react/src/lib/components/DeckGLMap/components/Map.tsx
> Fixed flickering of the viewport

- react/package-lock.json
- react/package.json
- react/src/lib/components/DeckGLMap/DeckGLMap.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
- react/src/lib/components/DeckGLMap/test/TestWrapper.tsx
- react/src/lib/components/GroupTree/test/TestWrapper.tsx
- react/src/lib/components/WellCompletions/test/TestWrapper.tsx
- react/src/lib/components/WellLogViewer/components/Scroller.tsx
> Typecheck error in DeckGlMap 

- react/src/lib/components/DeckGLMap/DeckGLMap.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
Initial version of callback for mouse events on DeckGL Map component
Get hover and click events.
See also https://github.com/equinor/webviz-subsurface-components/issues/875
> onMouseEvent callback for DeckGL Map component

- react/src/lib/components/DeckGLMap/components/Map.tsx
- react/src/lib/components/DeckGLMap/storybook/schemaValidation/DeckGLMapSchema.stories.jsx
- react/src/lib/components/DeckGLMap/storybook/schemaValidation/sampleData.js
- react/src/lib/inputSchema/ColorTables.json
- react/src/lib/inputSchema/schemaValidationUtil.tsx
- react/src/lib/inputSchema/validator.tsx
> Colortable schema

- react/src/lib/inputSchema/Wells.json
Avoid strict check on well properties
> Wells schema bug

- react/src/lib/components/DeckGLMap/storybook/schemaValidation/DeckGLMapSchema.stories.jsx
- react/src/lib/components/DeckGLMap/storybook/schemaValidation/sampleData.js
- react/src/lib/inputSchema/FaultPolygons.json
- react/src/lib/inputSchema/schemaValidationUtil.tsx
- react/src/lib/inputSchema/validator.tsx
> FaultPolygons validation

- react/src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
> Transparent well log where data is not defined 

- react/src/lib/components/DeckGLMap/layers/layersDefaultProps.ts
- react/src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
- react/src/lib/components/DeckGLMap/redux/types.ts
> Well name at top and bottom of trajectory

- react/src/lib/components/DeckGLMap/components/Map.tsx
Reverted change for orbit rotation #957
Handled view reset
> Reverted orbit axis change

- .github/workflows/webviz-subsurface-components.yml
> Enforce `lockfileVersion: 2` in CI

- react/package-lock.json
- react/package.json
Fixes regression causing error when rendering color legends.
> Downgrade @emerson-eps/color-tables package.

- react/src/lib/components/DeckGLMap/storybook/DeckGLMap.stories.jsx
> Map obscures text description in storybook docs

- react/src/lib/components/DeckGLMap/layers/intersection/intersectionView.stories.tsx
- react/src/lib/components/DeckGLMap/layers/intersection/unfoldedGeoJsonLayer.ts
- setup.py
> Use same layer to create unfolded view in Intersection view 

- react/src/lib/components/DeckGLMap/layers/grid/gridLayer.ts
Note: Currently the grid layer do not use ColorMapFunction.
> legend for grid layer

- react/.storybook/main.js
- react/package-lock.json
- react/package.json
- react/src/lib/components/DeckGLMap/DeckGLMap.stories.tsx
- react/src/lib/components/DeckGLMap/DeckGLMap.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
> Allow overriding tooltip

- react/src/lib/components/DeckGLMap/layers/axes/axesLayer.stories.tsx
- react/src/lib/components/DeckGLMap/layers/axes/axesLayer.ts
> custom label

- react/src/lib/components/DeckGLMap/layers/intersection/intersectionView.stories.tsx
- react/src/lib/components/DeckGLMap/layers/intersection/unfoldedGeoJsonLayer.ts
- react/src/lib/components/DeckGLMap/views/intersectionView.ts
Created storybook example with sample fence, surface and wells data
#1106
> Show unfolded fence in intersection view

- .github/workflows/webviz-subsurface-components.yml
- README.md
- setup.py
- webviz_subsurface_components/VectorCalculatorWrapper.py
- webviz_subsurface_components/VectorDefinitions.py
Closes https://github.com/equinor/webviz-subsurface-components/issues/1190.
> Drop Python `3.6` and `3.7` support

- react/src/lib/components/DeckGLMap/DeckGLMap.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
> Allow bounds to be passed as a callback.

- react/src/demo/example-data/volve_wells.json
- react/src/lib/components/DeckGLMap/components/InfoCard.test.tsx
- react/src/lib/components/DeckGLMap/components/InfoCard.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
- react/src/lib/components/DeckGLMap/components/__snapshots__/InfoCard.test.tsx.snap
> show unites in readout panel

- react/src/lib/components/DeckGLMap/layers/map/webworker.ts
> Fixes: "In MapLayer the NaN values are displayed as red #1216"

- react/src/lib/components/DeckGLMap/utils/fit-bounds.js
> remove console assert in fitBound file

- react/src/lib/components/DeckGLMap/layers/piechart/pieChartLayer.ts
- tests/test_deckgl_map.py
> Use correct number of dimensions in pie chart vectors

- react/src/lib/components/DeckGLMap/layers/axes/axesLayer.ts
- react/src/lib/components/DeckGLMap/layers/intersection/unfoldedGeoJsonLayer.ts
- react/src/lib/components/DeckGLMap/layers/northarrow/northArrow3DLayer.ts
- react/src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
See for example this discussion: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/269
> Make the test for 3d or 2d robust.

- react/src/lib/components/DeckGLMap/DeckGLMap.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
- react/src/lib/components/WellLogViewer/MapAndWellLogViewer.stories.jsx
- react/src/lib/components/WellLogViewer/MapAndWellLogViewer.tsx
- react/src/lib/components/WellLogViewer/SyncLogViewer.stories.jsx
- react/src/lib/components/WellLogViewer/SyncLogViewer.test.tsx
- react/src/lib/components/WellLogViewer/SyncLogViewer.tsx
- react/src/lib/components/WellLogViewer/WellLogViewer.stories.jsx
- react/src/lib/components/WellLogViewer/WellLogViewer.test.tsx
- react/src/lib/components/WellLogViewer/WellLogViewer.tsx
- react/src/lib/components/WellLogViewer/WellLogViewer_performance.test.tsx
- react/src/lib/components/WellLogViewer/__snapshots__/MapAndWellLogViewer.test.tsx.snap
- react/src/lib/components/WellLogViewer/components/WellLogSpacer.tsx
- react/src/lib/components/WellLogViewer/components/WellLogView.stories.jsx
- react/src/lib/components/WellLogViewer/components/WellLogView.test.tsx
- react/src/lib/components/WellLogViewer/components/WellLogView.tsx
- react/src/lib/components/WellLogViewer/components/WellLogViewWithScroller.stories.jsx
- react/src/lib/components/WellLogViewer/components/WellLogViewWithScroller.test.tsx
- react/src/lib/components/WellLogViewer/components/styles.scss
- react/src/lib/components/WellLogViewer/utils/deepcopy.ts
- react/src/lib/components/WellLogViewer/utils/pattern.tsx
- react/src/lib/components/WellLogViewer/utils/tracks.ts
- Fill color and pattern in tracks for wellpicks in WellLogView. See  #1096
- Add options to show/hide color or pattern int WellLogView and WellLogSpacer
- Redesign props for visual options WellLogView and WellLogSpacer
> WellPick fill color and pattern

- react/src/lib/components/DeckGLMap/layers/map/mapLayer.ts
Needed to use this class as a typed instance.
> Fixed typing conforming with DeckGL layers.

- react/package.json
- react/src/lib/components/DeckGLMap/components/ViewFooter.tsx
- react/tsconfig.dash.json
> Generate ViewFooter dash wrapper

- react/src/lib/components/DeckGLMap/DeckGLMap.stories.tsx
- react/src/lib/components/DeckGLMap/components/Map.tsx
- react/src/lib/components/DeckGLMap/storybook/DeckGLMap.stories.jsx
Fix the problem caused by empty view object as mentioned here:
Fixes #1231
> bug fixing for empty view object

- react/src/lib/components/SubsurfaceViewer/components/Map.tsx
Earlier I belive it was always at least an empty object but now it mau be undefined.
> Had to update several test on existence of cameraProperty.

- react/src/lib/components/SubsurfaceViewer/SubsurfaceViewer.stories.tsx
- react/src/lib/components/SubsurfaceViewer/SubsurfaceViewer.tsx
- react/src/lib/components/SubsurfaceViewer/components/Map.test.tsx
- react/src/lib/components/SubsurfaceViewer/components/Map.tsx
- react/src/lib/components/WellLogViewer/MapAndWellLogViewer.tsx
> Allow generic layers in SubsurfaceViewer

- react/src/lib/components/SubsurfaceViewer/SubsurfaceViewer.stories.tsx
- react/src/lib/components/SubsurfaceViewer/components/Map.tsx
- react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.stories.tsx
- react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.ts
Also added a story to demonstrate the different contour line behaviours.
Fixes #1446
CC @t0oF-azpn
> Fix contour line calculation when using "meshData" prop

- react/src/lib/components/SubsurfaceViewer/SubsurfaceViewer.stories.tsx
- react/src/lib/components/SubsurfaceViewer/components/Map.tsx
Also some refactoring towards fixing #1459
> Added a story to demonstrate views synchronization

- react/src/lib/components/SubsurfaceViewer/components/Map.tsx
Refactoring towards fixing #1459
> Moved min and max zoom out of Views type.

- react/src/lib/components/SubsurfaceViewer/components/Map.tsx
- react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.stories.tsx
Removed state to capture the center of data. Also fix some hook dependencies
> Remove the state/useState  "center" as it is not needed.

- react/src/lib/components/SubsurfaceViewer/components/Map.tsx
- react/src/lib/components/SubsurfaceViewer/layers/grid3d/grid3dLayer.ts
- react/src/lib/components/SubsurfaceViewer/layers/grid3d/webworker.ts
- react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.stories.tsx
This is because the data may be changed by the layer (multiply --1 on z values) and changes should not be reflected on the outside of the layer.
> If input data are given as arrays they should be copied.

- typescript/packages/subsurface-viewer/src/SubsurfaceViewer.stories.tsx
- typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
- typescript/packages/subsurface-viewer/src/components/Map.tsx
Works with maplayer
Includes maplayer, grid23Dlayer and triangleLayer.
typecheck fixes
Code comment fixes.
lint fix
test
Code comment fix.
code commit fix
Code comment fixes.
Add callback which will be called after all layers are loaded.
Works with maplayer
Includes maplayer, grid23Dlayer and triangleLayer.
typecheck fixes
Code comment fixes.
test
code commit fix
Code comment fixes.
In progress
In progress
> Add callback which will be called after all layers are loaded.

- typescript/packages/well-log-viewer/src/components/WellLogView.tsx
- typescript/packages/well-log-viewer/src/utils/tracks.ts
Workaround of wrong behavior of videx wellog component
Closes #1492
> Refresh well log track title tooltip after interactive editing

- .github/dependabot.yml
Config dependabot to use conventional commits.
Fixes #1669
> build: added dependabot config

- typescript/packages/subsurface-viewer/src/SubsurfaceViewer.stories.tsx
- typescript/packages/subsurface-viewer/src/components/Map.tsx
- for some reason this has gone missing from the code at some point.
> fix: View resets to default when adding/removing a layer. #1690

- .github/workflows/typescript.yml
Second tentative: move directory instead of copying it.
> ci: fix Update Storybook script

- typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/layers/grid3d/privateLayer.ts
- typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
- also ZIncreasingDownward flag not correct in Grid3DLayer story.
> fix: Grid3DLayer and MapLayer;  Depth readout not reported for value 0

- typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
Revert change introduced by PR #1729.
> fix: infinite loop when rendering Grid3D layer

- typescript/packages/subsurface-viewer/src/layers/grid3d/fragment.fs.glsl.ts
- typescript/packages/subsurface-viewer/src/layers/map/fragment.fs.glsl.ts
- typescript/packages/subsurface-viewer/src/layers/triangle/fragment.fs.glsl.ts
Previous PR had a title that does not trigger a semantic release.
> fix: force publishing a new package

- typescript/packages/subsurface-viewer/src/layers/map/mapLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/layers/map/mapLayer.ts
- typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
- typescript/packages/subsurface-viewer/src/layers/map/vertex.glsl.ts
Also added a story to demonstrate clipping.
> fix: honor deck.gl extensions in MapLayer

- typescript/packages/subsurface-viewer/src/layers/points/fragment.glsl.ts
- typescript/packages/subsurface-viewer/src/layers/points/pointsLayer.stories.tsx
- typescript/packages/subsurface-viewer/src/layers/points/pointsLayer.ts
- typescript/packages/subsurface-viewer/src/layers/points/privatePointsLayer.ts
- typescript/packages/subsurface-viewer/src/layers/points/vertex.glsl.ts
- typescript/packages/subsurface-viewer/src/layers/utils/layerTools.ts
1) For performance boost the layer applies ZIncreasingDownwards in the vertex shader.
2) depthTest flag is added in the layer API.
3) Fixed crash in the story book when a property of the layer is changed.
> feat(PointsLayer):  ZIncreasingDownwards is applied in vertex shader, depthTest flag added

- typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
- typescript/packages/well-log-viewer/src/components/WellLogView.tsx
Refill callback array when increasing number of welllogs
closes #1780
> fix: Refill SyncLogViewer vew callbacks array on template array changing

- typescript/packages/subsurface-viewer/src/components/Map.tsx
Fix regression in viewport size introduced in PR #1837
> fix: regression in viewport size

- typescript/package-lock.json
- typescript/packages/subsurface-viewer/package.json
Caused build error in Semantic release CI
> fix: add missing dependencies

- typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
Fix a crash when removing Well Log from props in SLV
close #2114
> fix: Crash Removing Well Log in SLV

- typescript/package-lock.json
- typescript/package.json
Last published package by semantic release was June 24th. @nx/jest was bumped on June 25th.
No new package has been published meanwhile.
There might be a relationship, or not. But it is worth trying, until anyone having the knowledge and rights to fix the situation is back...
> fix: semantic release not publishing

- typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
- typescript/packages/subsurface-viewer/src/components/DistanceScale.test.tsx
- typescript/packages/subsurface-viewer/src/components/DistanceScale.tsx
- typescript/packages/subsurface-viewer/src/components/Map.tsx
- typescript/packages/subsurface-viewer/src/storybook/components/DistanceScale.stories.tsx
Prevent console deprecation errors.
> fix: remove defaultProps from function components

- typescript/.nxreleaserc.json
Should trigger major version bump.
> ci: add release rules for breaking "feat!" and "fix!" prefixes

- typescript/packages/subsurface-viewer/src/layers/colormap/colormapLayer.ts
- typescript/packages/subsurface-viewer/src/layers/utils/layerTools.ts
> fix: incorrect interface of `ColormapLayer`

- typescript/package-lock.json
- typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
> fix: wellNamePosition behavior is inverted when specifying a boolean

- .github/workflows/semantic_release.yml
- typescript/package-lock.json
`nx release version` corrupts `package-lock.json`.
Nx bug: https://github.com/nrwl/nx/issues/22066
Suggested workaround: https://github.com/nrwl/nx/issues/22066#issuecomment-2576366862
> ci: prevent corrupting package-lock.json in `nx release`.
